/**
 * Statuts d'un dossier, miroir de l'enum backend tn.econstruction.enums.ApplicationStatus.
 */
export const ApplicationStatus = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ADDITIONAL_DOCUMENTS_REQUIRED: 'ADDITIONAL_DOCUMENTS_REQUIRED',
  ADDITIONAL_DOCUMENTS_PROVIDED: 'ADDITIONAL_DOCUMENTS_PROVIDED',
  FORWARDED_TO_SECRETARY: 'FORWARDED_TO_SECRETARY',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CLOSED_WITHOUT_ACTION: 'CLOSED_WITHOUT_ACTION',
  TACIT_APPROVAL: 'TACIT_APPROVAL',
}
