/**
 * Types de documents, miroir de l'enum backend tn.econstruction.enums.DocumentType.
 */
export const DocumentType = {
  OFFICIAL_FORM: 'OFFICIAL_FORM',
  PROPERTY_TITLE: 'PROPERTY_TITLE',
  LOCATION_PLAN: 'LOCATION_PLAN',
  SITE_PLAN: 'SITE_PLAN',
  ARCHITECTURAL_PLANS: 'ARCHITECTURAL_PLANS',
  DESCRIPTIVE_NOTE: 'DESCRIPTIVE_NOTE',
  OACA_CERTIFICATE: 'OACA_CERTIFICATE',
  GEOTECHNICAL_STUDY: 'GEOTECHNICAL_STUDY',
  UTILITY_PROVIDERS_APPROVAL: 'UTILITY_PROVIDERS_APPROVAL',
  TAX_RECEIPT: 'TAX_RECEIPT',
  OTHER: 'OTHER',
}
